= Serial_heat_transfer_design

*Isaías Alfaro Ugalde <isaias.alfaro@ucr.ac.cr>*

---

:experimental:
:nofooter:
:source-highlighter: highlight.js
:sectnums:
:stem: latexmath
:toc:
:xrefstyle: short

== Diseño

image::./images/UML.svg[UML]

---

* *Array*: Al simular una lámina, buscamos recrearla en un programa con cierta exactitud respecto a una lámina en la vida real. Para ello, se opto por utilizar un arreglo unidimensional que simula una mtriz. Esto se puede ver como si se juntaran todas las filas de la matriz en una sola fila.

image::images/Memoria.svg[]

Aqui vemos como un ejemplo de como se veria el array guardado en memoria. En este caso, la matriz es de 3x4, por lo que se tienen 12 campos y vemos como cada fila se va guardando de una forma seguida. 

=== Structs

El color morado pertenece a estos structs.

heat:: Esta estructura se utiliza para la matriz en la que se almacenan los dos momentos de calor, permitiendo avanzar en la simulación. Esto se debe a que se requieren tanto el estado actual como el siguiente momento, luego de completar un ciclo de simulación.

data_job:: Esta estructura almacena los datos de la placa y otros parámetros necesarios para la simulación actual. Se va sobreescribiendo a medida que avanzan las pruebas.

data_array:: Esta estructura contiene todos los datos extraídos del archivo job, con el propósito de abrir el archivo solo una vez y evitar operaciones repetidas de lectura.

=== Structs de hilos

El color naranja pertenece a estos structs.

shared_data:: Estructura que contiene los datos que van a compartir los hilos para su ejecución.

private_data:: Estructura que contiene los datos privados del hilo y puntero al mismo.

---

image::./images/Threats.svg[Hilos]

En este UML se quiere ejemplificar como es que estan trabajando los hilos, la funcion heat_team(verde) crea un equipo de hilos que son ejemplificados con las lineas azules, estos son enviados a trabajar en la matriz que se ejemplifica con las celdas negras y aplican la formula de calor que es la funcion make_heat, por ultimo cuando se termina el trabajo la funcion de heat_team elimina los hilos trabajadores y reporta el resultado de la matriz.

== OpenMP y MPI
OpenMP y MPI son dos tecnologías utilizadas para la programación paralela, cada una con sus propias características y propósitos.

OpenMP es una API que permite la programación paralela en C, C++ y Fortran. En este caso, se utiliza para paralelizar el proceso de simulación de calor en la lámina. Se emplean directivas de OpenMP para dividir el trabajo entre múltiples hilos, lo que mejora el rendimiento y reduce el tiempo de ejecución.

MPI (Message Passing Interface) es un estándar para la comunicación entre procesos en sistemas distribuidos. En este caso, se utiliza para permitir que los hilos se comuniquen entre sí y compartan datos durante la simulación. MPI facilita la sincronización y la transferencia de información entre los hilos, lo que es esencial para garantizar que todos trabajen con los mismos datos y resultados.

=== Metodos

Los metodos vistos en el UML son los metodos que tienen que ver con la simulacion de calor.

Make_data:: Crea y gestiona los datos para la simulación de calor. Asigna memoria para las estructuras necesarias, llama a las funciones para encontrar archivos, cargar datos y crear matrices.

Make_matrix:: Crea la matriz de datos de calor y gestiona el proceso de simulación. Llama a las funciones para cargar datos y crear matrices de calor

Heat_team:: Crea un equipo de hilos, estos son enviados a trabjar una fila especifica de la placa.

Make_heat:: Calcula y actualiza la distribución de calor en la placa. Utiliza el método de difusión para calcular la distribución del calor en la placa.

job_out_file:: Escribe los resultados en el archvio job y su respectivo plate.

== Solución es pseudocodigo

[#pseudocode]
[source,delphi]
----
include::matrix.pseudo[]
----
